export default function Terms() {
  return (
    <div style={{ maxWidth: '800px', margin: '0 auto', padding: '40px 20px', color: '#e0e0f0' }}>
      <h1 style={{ fontSize: '28px', fontWeight: 700, marginBottom: '8px' }}>Terms of Service</h1>
      <p style={{ color: '#8080a0', fontSize: '14px', marginBottom: '32px' }}>Last updated: May 2026</p>

      <section style={{ marginBottom: '32px' }}>
        <h2 style={{ fontSize: '20px', fontWeight: 600, marginBottom: '12px' }}>Acceptable Use</h2>
        <p>You may use Knowledge Factory solely for legitimate hiring and candidate evaluation purposes. You may not reverse engineer, scrape, or misuse the platform's AI-generated content for purposes outside the hiring process.</p>
      </section>

      <section style={{ marginBottom: '32px' }}>
        <h2 style={{ fontSize: '20px', fontWeight: 600, marginBottom: '12px' }}>Account Responsibility</h2>
        <p>You are responsible for maintaining the confidentiality of your login credentials. All activity under your account is your responsibility.</p>
      </section>

      <section style={{ marginBottom: '32px' }}>
        <h2 style={{ fontSize: '20px', fontWeight: 600, marginBottom: '12px' }}>AI-Generated Content</h2>
        <p>Interview questions and assessments generated by our AI are provided as-is. We do not guarantee their accuracy or suitability. Review all generated content before presenting it to candidates.</p>
      </section>

      <section style={{ marginBottom: '32px' }}>
        <h2 style={{ fontSize: '20px', fontWeight: 600, marginBottom: '12px' }}>Termination</h2>
        <p>We reserve the right to suspend or terminate accounts that violate these terms or engage in abusive behavior toward candidates.</p>
      </section>

      <section style={{ marginBottom: '32px' }}>
        <h2 style={{ fontSize: '20px', fontWeight: 600, marginBottom: '12px' }}>Contact</h2>
        <p>Email: <a href="mailto:shalem@knowledge-factory.com" style={{ color: '#8b5cf6' }}>shalem@knowledge-factory.com</a></p>
      </section>
    </div>
  );
}