"""Proctoring configuration and weights."""

# Risk Weights
TAB_SWITCH_WEIGHT = 10
TAB_SWITCH_REPEATED_WEIGHT = 15
TAB_SWITCH_FREQUENT_WEIGHT = 25

WINDOW_BLUR_WEIGHT = 5
WINDOW_BLUR_REPEATED_WEIGHT = 10
WINDOW_BLUR_FREQUENT_WEIGHT = 20

COPY_WEIGHT = 10
PASTE_WEIGHT = 20

DEVTOOLS_WEIGHT = 40

NO_FACE_WEIGHT = 15
MULTIPLE_PERSONS_WEIGHT = 25

HEAD_POSE_WEIGHT = 8
HEAD_POSE_REPEATED_WEIGHT = 15

VOICE_DETECTED_WEIGHT = 20
CONTINUOUS_CONVERSATION_WEIGHT = 35

PHONE_DETECTED_WEIGHT = 80
FULLSCREEN_EXIT_WEIGHT = 20

# Risk Policy
RISK_TERMINATION_THRESHOLD = 100
RISK_DECAY_PERCENT = 0.0  # Purely cumulative
RISK_DECAY_INTERVAL = 60

# Session Configuration
FRAME_CAPTURE_INTERVAL = 1.0  # Seconds
DEBOUNCE_INTERVAL = 5.0       # Ignore duplicate events within 5 seconds
WEBSOCKET_HEARTBEAT_TIMEOUT = 30
HIGH_RISK_AUTO_TERMINATE = True
