"""Proctoring configuration and weights."""

# Risk Weights
TAB_SWITCH_WEIGHT = 10
COPY_PASTE_WEIGHT = 10
WINDOW_BLUR_WEIGHT = 15
NO_FACE_WEIGHT = 20
VOICE_DETECTED_WEIGHT = 15
MULTIPLE_PERSONS_WEIGHT = 60
PHONE_DETECTED_WEIGHT = 80
FULLSCREEN_EXIT_WEIGHT = 20

# Risk Policy
RISK_TERMINATION_THRESHOLD = 100
RISK_DECAY_PERCENT = 0.05  # 5% decay
RISK_DECAY_INTERVAL = 10   # Every 10 seconds

# Session Configuration
FRAME_CAPTURE_INTERVAL = 1.0  # Seconds
DEBOUNCE_INTERVAL = 5.0       # Ignore duplicate events within 5 seconds
WEBSOCKET_HEARTBEAT_TIMEOUT = 30
HIGH_RISK_AUTO_TERMINATE = True
